### PR TITLE
add speed limit parameters

### PR DESCRIPTION
**Pull request by TrazCobalt**
Add speed limit and turn rate limit parameters.

Also trying to upstream: https://github.com/ros-teleop/teleop_twist_keyboard/pull/34

### CODE REVIEW

**Comment by TrazCobalt** [comment]
@kodie-artner for review

**Review by kodie-artner — APPROVED** [review]
Cool, looks good. This is only for eng tele-op dangerous though right? Did someone turn the speed up too high?

**Comment by TrazCobalt** [comment]
@kodie-artner see https://github.com/cobalt-robotics/cobalt_code/pull/8081
Adding a low speed limit specialist-teleop-dangerous mode

Going to try to upstream change this then go back to using the upstream repository since it looks like it's the same as this repository now.
If Mr Trainman doesn't want to merge this change, then we should actually probably make a new fork that lives in cobalt_robotics and merge the change there, come to think of it.

**Comment by kodie-artner** [comment]
I see, I don't love the controls for specialist use. If we want this to be more than just an occasional tool for devs then yes I suggest we fork in cobalt and make some real changes. This fork was always meant to be temporary.

**Comment by TrazCobalt** [comment]
@kodie-artner 
Setting aside the operation question regarding specialist use, I did get this change successfully upstreamed:
https://github.com/ros-teleop/teleop_twist_keyboard/pull/34/files

I'll point our brobots back at the latest upstream

**Pull request closed without merging**
